skills_db = {

    "HR": [

        "recruitment",
        "talent acquisition",
        "employee relations",
        "hr policies",
        "onboarding",
        "payroll",
        "performance management",
        "training",
        "leadership",
        "communication",
        "team management",
        "conflict resolution",
        "interviewing",
        "organizational development",
        "hr analytics",
        "employee engagement",
        "compliance",
        "benefits administration",
        "workforce planning",
        "time management"

    ],

    "Data Science": [

        "python",
        "machine learning",
        "deep learning",
        "data analysis",
        "data visualization",
        "tensorflow",
        "keras",
        "pytorch",
        "pandas",
        "numpy",
        "matplotlib",
        "seaborn",
        "sql",
        "statistics",
        "nlp",
        "computer vision",
        "power bi",
        "tableau",
        "excel",
        "big data",
        "data mining",
        "predictive modeling",
        "scikit-learn",
        "artificial intelligence",
        "feature engineering",
        "classification",
        "regression",
        "clustering"

    ],

    "IT": [

        "networking",
        "cybersecurity",
        "linux",
        "windows server",
        "cloud computing",
        "aws",
        "azure",
        "docker",
        "kubernetes",
        "system administration",
        "technical support",
        "hardware troubleshooting",
        "software installation",
        "virtualization",
        "database management",
        "firewalls",
        "vpn",
        "tcp/ip",
        "active directory",
        "it support",
        "server management",
        "network security",
        "cloud security",
        "automation",
        "devops"

    ],

    "Python Developer": [

        "python",
        "django",
        "flask",
        "fastapi",
        "rest api",
        "api development",
        "sql",
        "mysql",
        "postgresql",
        "mongodb",
        "oop",
        "data structures",
        "algorithms",
        "git",
        "github",
        "docker",
        "linux",
        "html",
        "css",
        "javascript",
        "streamlit",
        "automation",
        "web scraping",
        "selenium",
        "pandas",
        "numpy",
        "pytest",
        "debugging",
        "json",
        "multithreading"

    ]
}
